app = "oncall-navigator"
primary_region = "dfw"

[build]
  image = "registry.fly.io/oncall-navigator:deployment-0dba6c96fa37cc8a32e193a550a40d85"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  interval = 15000
  timeout = 2000
  grace_period = "10s"
  method = "GET"
  path = "/health"
